---
Name: discoverer-bifrost
Only:
    envvarset: 'BIFROST_PUBLIC_API_KEY'
---
SilverStripe\Core\Injector\Injector:
    Elastic\EnterpriseSearch\Client.searchClient:
        factory: SilverStripe\DiscovererBifrost\Service\ClientFactory
        constructor:
            host: '`BIFROST_ENDPOINT`'
            token: '`BIFROST_PUBLIC_API_KEY`'
            http_client: '%$GuzzleHttp\Client'
